### ISSUE TITLE
Support for Tetris Forever?

### ISSUE THREAD

**Issue by Ecdldaiiere** [Masquerade64/Cowabunga#11]
Hello, glad I found this handy tool to apparently look into all the assets of Digital Eclipse games. Wondering if there will soon be support for the latest Digital Eclipse game "Tetris Forever".

**Comment by MaximFrancev** [comment]
The key for Tetris Forever is the same as Jeff Minter.

**Comment by Masquerade64** [comment]
The key for Teris Forever is the same as Jeff Minter.
