### ISSUE TITLE
Add Support for Mighty Morphin Power Rangers: Rita's Rewind

### ISSUE THREAD

**Issue by mfaathirarsa** [Masquerade64/Cowabunga#12]
**Game Information:**  
- **Name:** Mighty Morphin Power Rangers: Rita's Rewind  
- **Steam Page:** [https://store.steampowered.com/app/2816870/Mighty_Morphin_Power_Rangers_Ritas_Rewind/](https://store.steampowered.com/app/2816870/Mighty_Morphin_Power_Rangers_Ritas_Rewind/)  

**Description:**  
This tool has been extremely helpful for working with Digital Eclipse games. _Mighty Morphin Power Rangers: Rita's Rewind_ appears to use the same `.pie` file format as other supported games. It would be great to add compatibility for decrypting and working with its assets.

**Comment by mfaathirarsa** [comment]
I have found that the key is 0xFA5E893B and it works
i hope you will add this key to your future release

**Comment by Masquerade64** [comment]
Added in Release 0.9.0. Thank you for your contribution to this project.

**Comment by Masquerade64** [comment]
Added in Release 0.9.0. Thank you for your contribution to this project.

**Comment by nekkk** [comment]
Hi. Sorry to reply this thread, but it seems encryption is not working, it throws an error by trying to return .zip to .pie
![error](https://github.com/user-attachments/assets/ddcf21ce-5476-4fb3-afc1-aa3642cbde2f)

**Comment by leafmineraltown** [comment]
This one is my fault I'll fix it
