### ISSUE TITLE
Use cowabunga to create assets.pie from assets.zip

### ISSUE THREAD

**Issue by LerainL** [Masquerade64/Cowabunga#2]
Greetings

Can I use this tool both ways - to create assets.pie from assets.zip ?

Example:
cowabunga64.exe --key cowabunga assets.zip assets.pie

The creation process seems to work.
It will create an "assets.pie" with correct size, but the game wont start with it and it will stop responding.

Gratitude

**Comment by Masquerade64** [comment]
Hi,
The tool does work both ways. The game should run fine if you are using the correct key for the game.

**Comment by LerainL** [comment]
Found the problem.

"Atari 50 - The Anniversary Celebration" have external "assets" folder containing sub-folder "vortex" with some DLLs.

By mistake I've packed those as well in the "assets.pie" and that made the game crash.

Leaving them outside of the pack works as a charm.

**Comment by Laxmewl** [comment]
I am experiencing a similar issue with Tetris Forever. Not sure what I am doing wrong. Would like to confirm if it's a me problem or not. Thanks.
