### ISSUE TITLE
Atari 50 DLC 2

### ISSUE THREAD

**Issue by DrAzathoth** [Masquerade64/Cowabunga#8]
You know the drill. DLC 2 "The First Console War" for Atari 50 is out.

Also, I just wanna say thank you, @Masquerade64, for all your hard work maintaining this tool.

**Comment by Masquerade64** [comment]
I'll check it out, thanks for letting me know.

**Comment by Masquerade64** [comment]
Please see release 0.8.0 for support of The First Console War.
