### ISSUE TITLE
Tetris Forever

### ISSUE THREAD

**Issue by Fabs-tinkers** [Masquerade64/Cowabunga#9]
Hey! First of all, thanks for the tool and special thanks for the quick reaction to new content. Now... any chance Today released "Tetris Forever" content can be used with this tool? it has assets.pie in it. Thank you. No hurry!

**Comment by Masquerade64** [comment]
The key for Tetris Forever is the same key as used in Llamasoft: The Jeff Minter Story.

Just do:

`cowabunga64.exe -k jeff-minter assets.pie assets.zip`

And you will get your decrypted output.

**Comment by Fabs-tinkers** [comment]
Nice! Thanks!
